apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uptime-kuma-secret
  namespace: six-degrees-apps
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: uptime-kuma-secret
    creationPolicy: Owner
  data:
    - secretKey: UPTIME_KUMA_DB_TYPE
      remoteRef:
        key: six-degrees/uptime-kuma/secrets
        property: UPTIME_KUMA_DB_TYPE
    - secretKey: UPTIME_KUMA_DB_HOSTNAME
      remoteRef:
        key: six-degrees/uptime-kuma/secrets
        property: UPTIME_KUMA_DB_HOSTNAME
    - secretKey: UPTIME_KUMA_DB_PORT
      remoteRef:
        key: six-degrees/uptime-kuma/secrets
        property: UPTIME_KUMA_DB_PORT
    - secretKey: UPTIME_KUMA_DB_NAME
      remoteRef:
        key: six-degrees/uptime-kuma/secrets
        property: UPTIME_KUMA_DB_NAME
    - secretKey: UPTIME_KUMA_DB_USERNAME
      remoteRef:
        key: six-degrees/uptime-kuma/secrets
        property: UPTIME_KUMA_DB_USERNAME
    - secretKey: UPTIME_KUMA_DB_PASSWORD
      remoteRef:
        key: six-degrees/uptime-kuma/secrets
        property: UPTIME_KUMA_DB_PASSWORD
