apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
spec:
  project: default
  source:
    chart: kong
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.47.0
    helm:
    valueFiles:
    - values.yaml

  destination:
    name: "in-cluster"
    namespace: kong
