apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-db-secret
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kong-db-secret
    creationPolicy: Owner
  data:
    - secretKey: pg_database
      remoteRef:
        key: kong_db_secret
        property: pg_database
    - secretKey: pg_host
      remoteRef:
        key: kong_db_secret
        property: pg_host
    - secretKey: pg_password
      remoteRef:
        key: kong_db_secret
        property: pg_password
    - secretKey: pg_port
      remoteRef:
        key: kong_db_secret
        property: pg_port
    - secretKey: pg_user
      remoteRef:
        key: kong_db_secret
        property: pg_user