# Define Helm repository sources
repositories:
  - name: rancher-stable
    url: https://releases.rancher.com/server-charts/stable
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: jetstack
    url: https://charts.jetstack.io

# Define Helm releases to be installed
releases:
  - name: namespaces
    chart: ./namespaces
    version: 0.1.0
    namespace: default

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.14.0
    needs:
      - default/namespaces
    values:
      - cert-manager/values.yaml

  - name: certificates
    namespace: cert-manager
    chart: ./certificates
    needs:
      - cert-manager/cert-manager
    values:
      - certificates/values.yaml

  # Add Rancher
  - name: rancher
    namespace: cattle-system
    chart: rancher-latest/rancher
    version: 2.10.1
    needs:
      - cert-manager/certificates
    values:
      - rancher/values.yaml
