# Define Helm repository sources
repositories:
  - name: rancher-latest
    url: https://releases.rancher.com/server-charts/stable
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: jetstack
    url: https://charts.jetstack.io

# Define Helm releases to be installed
releases:
  # Install cert-manager
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.14.0
    values:
      - cert-manager/values.yaml

  # Install Rancher
  - name: rancher
    namespace: cattle-system
    chart: rancher-latest/rancher
    version: 2.10.1
    values:
      - rancher/values.yaml

  # Install ArgoCD
  - name: argocd
    namespace: management
    chart: argo/argo-cd
    version: 5.36.0
    values:
      - argocd/values.yaml

  # Install Vault
  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.24.0
    values:
      - vault/values.yaml
