grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.6degrees.com.sa
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.6degrees.com.sa
    annotations:
      cert-manager.io/cluster-issuer: "http01-clusterissuer"
  
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-operated.monitoring:9090
          isDefault: true
        - name: Loki
          type: loki
          url: http://loki-gateway.monitoring:80
  
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default 

  dashboards:
    default:
      kubernetes-cluster:
        json: |
          {{ .Files.Get "dashboards/kubernetes-cluster.json" | nindent 10 }}
  
  # Add admin password
  adminPassword: "admin"  # Change this in production
  
  persistence:
    enabled: true
    size: 10Gi 