loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    retention:
      time: 168h  # 7 days
      size: 10GB
  limits_config:
    retention_period: 168h
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
    max_query_length: 721h
    max_query_parallelism: 32
  chunk_store_config:
    max_look_back_period: 168h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: filesystem
    compaction_interval: 10m
    retention_enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi 