apiVersion: apps/v1
kind: Deployment
metadata:
  name: logto
  namespace: six-degrees-apps
  labels:
    app: logto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: logto
  template:
    metadata:
      labels:
        app: logto
    spec:
      volumes:
        - name: connectors
          persistentVolumeClaim:
            claimName: logto-connectors
      initContainers:
        - image: ghcr.io/logto-io/logto
          command:
            - /bin/sh
          args:
            - '-c'
            - 'npm run cli connector add -- --official'
          name: init
          volumeMounts:
            - name: connectors
              mountPath: /etc/logto/connectors
      containers:
        - image: ghcr.io/logto-io/logto
          name: logto
          volumeMounts:
            - name: connectors
              mountPath: /etc/logto/connectors
          envFrom:
            - secretRef:
                name: logto-secrets
            - configMapRef:
                name: logto-configmap
      livenessProbe:
        httpGet:
          path: /api/status
          port: 3001
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
      readinessProbe:
        httpGet:
          path: /api/status
          port: 3001
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3



