apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: logto-secrets
  namespace: logto
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: logto-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: six-degrees/logto/secrets
        property: DB_URL