apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logto-connectors
  namespace: six-degrees-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi 