apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: windmill-db-secret
  namespace: windmill
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: windmill-db-secret
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: windmill_db_secret
        property: url