windmill:
  baseDomain: windmill.6degrees.com.sa
  baseProtocol: https
  databaseUrlSecretName: "windmill-db-secret"
  databaseUrlSecretKey: url
  appReplicas: 1
  lspReplicas: 1
  workerGroups:
    - name: "default"
      replicas: 1
      extraEnv:
        - name: "INIT_SCRIPT"
          value: "apt-get update && apt-get install -y chromium"
        - name: "WORKER_TAGS"
          value: "chromium"
    - name: "native"
      replicas: 0

postgresql:
  enabled: false

ingress:
  className: "nginx"
  annotations: {
    cert-manager.io/cluster-issuer: "http01-clusterissuer"
  }
  tls:
    - hosts:
        - "windmill.6degrees.com.sa"
      secretName: windmill-tls-cert