apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-ui-secret
  namespace: longhorn
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-ui-secret
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: longhorn-ui-secret
        property: auth
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-s3-secret
  namespace: longhorn
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: longhorn-s3-secret
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: longhorn-s3-secret
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: longhorn-s3-secret
        property: AWS_ENDPOINTS
    - secretKey: VIRTUAL_HOSTED_STYLE
      remoteRef:
        key: longhorn-s3-secret
        property: VIRTUAL_HOSTED_STYLE
