ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.6degrees.com.sa
  tls: true
  secureBackends: true
  tlsSecret: longhorn-6degrees-tls
  path: /
  pathType: ImplementationSpecific
  annotations:
    cert-manager.io/cluster-issuer: http01-clusterissuer
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: longhorn-ui-secret
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"

defaultBackupStore:
  # -- Endpoint used to access the default backupstore. (Options: "NFS", "CIFS", "AWS", "GCP", "AZURE")
  backupTarget: "s3://longhorn-6degrees@hel1/"
  # -- Name of the Kubernetes secret associated with the default backup target.
  backupTargetCredentialSecret: longhorn-s3-secret
