apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    app: rancher
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-global-data
  labels:
    app: rancher
---
apiVersion: v1
kind: Namespace
metadata:
  name: management
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault 