apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: argocd
spec:
  project: 6degrees
  source:
    repoURL: https://github.com/degree-0/6degrees-management-cluster.git
    targetRevision: HEAD
    path: cluster-config
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 