apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - name: prometheus
            path: monitoring/prometheus
            namespace: monitoring
            repoURL: https://prometheus-community.github.io/helm-charts
            chart: kube-prometheus-stack
            version: 55.5.0
          - name: grafana
            path: monitoring/grafana
            namespace: monitoring
            repoURL: https://grafana.github.io/helm-charts
            chart: grafana
            version: 7.0.17
          - name: loki
            path: monitoring/grafana
            namespace: monitoring
            repoURL: https://grafana.github.io/helm-charts
            chart: loki
            version: 5.41.0
  template:
    metadata:
      name: "monitoring-{{ .name }}"
      namespace: argocd
    spec:
      project: 6degrees
      source:
        repoURL: "{{ .repoURL }}"
        chart: "{{ .chart }}"
        targetRevision: "{{ .version }}"
        helm:
          valueFiles:
            - "{{ .path }}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 