apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # External secrets should be wave 0
spec:
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: kong
  spec:
    destination:
      name: ''
      namespace: kong
      server: https://kubernetes.default.svc
    source:
      path: ''
      repoURL: https://charts.konghq.com
      targetRevision: 2.47.0
      chart: kong
      helm:
        valueFiles:
          - values.yaml
    sources: []
    project: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - Replace=true
