apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # External secrets should be wave 0
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: 2.29.0
    chart: kong
    helm:
      valueFiles:
        - chart/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true