apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: 2.47.0
    helm:
      valuesFile: ./values.yaml
    chart: kong
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true