apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-auth-secret
  namespace: kong
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kong-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: kong/auth-secret
        property: auth
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-db-secret
  namespace: kong
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kong-db-secret
    creationPolicy: Owner
  data:
    - secretKey: KONG_PG_DATABASE
      remoteRef:
        key: kong/db-secret
        property: PG_DATABASE
        
    - secretKey: KONG_PG_HOST
      remoteRef:
        key: kong/db-secret
        property: PG_HOST

    - secretKey: KONG_PG_PASSWORD
      remoteRef:
        key: kong/db-secret
        property: PG_PASSWORD

    - secretKey: KONG_PG_PORT
      remoteRef:
        key: kong/db-secret
        property: PG_PORT

    - secretKey: KONG_PG_USER
      remoteRef:
        key: kong/db-secret
        property: PG_USER
