apiVersion: v2
name: kube-prometheus-stack
description: Prometheus Stack for 6Degrees Management Cluster
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 55.5.0
    repository: https://prometheus-community.github.io/helm-charts 