kube-prometheus-stack:
  grafana:
    enabled: false  # We'll use separate Grafana installation
  prometheus:
    prometheusSpec:
      retention: 15d
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
  alertmanager:
    alertmanagerSpec:
      retention: 120h
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi 